services:
  web:
    build:
      context: .
      target: runner
    restart: unless-stopped
    ports:
      - 3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
